model_list:
  - model_name: gpt-4
    litellm_params:
      model: openai/gpt-4
      api_key: sk-live-4f9a8b7c6d5e4f3a2b1c
general_settings:
  master_key: sk-master-abcdef1234567890
guardrails:
  - guardrail_name: pii-mask
    litellm_params:
      guardrail: presidio
      mode: pre_call
